#!/usr/bin/env bash

#get the path to this directory
BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#link all the files
ln -s "$BASEDIR/Xresources" ~/.Xresources
mkdir -p ~/.config
ln -s "$BASEDIR/openbox" ~/.config/
ln -s "$BASEDIR/awesome" ~/.config/
mkdir -p ~/.config/tint2
ln -s "$BASEDIR/tint2rc" ~/.config/tint2
mkdir -p ~/.config/dunst
ln -s "$BASEDIR/dunstrc" ~/.config/dunst
ln -s "$BASEDIR/bashrc" ~/.bashrc
ln -s "$BASEDIR/vimrc" ~/.vimrc
ln -s "$BASEDIR/bash_aliases" ~/.bash_aliases
ln -s "$BASEDIR/inputrc" ~/.inputrc
ln -s "$BASEDIR/profile" ~/.profile
ln -s "$BASEDIR/gtkrc-2.0" ~/.gtkrc-2.0
ln -s "$BASEDIR/gtk-3.0/settings.ini" ~/.config/gtk-3.0/settings.ini
ln -s "$BASEDIR/gtk-3.0/gtk.css" ~/.config/gtk-3.0/gtk.css
ln -s "$BASEDIR/xprofile" ~/.xprofile
ln -s "$BASEDIR/termiteconf" ~/.config/termite/config
ln -s "$BASEDIR/fonts.conf" ~/.config/fontconfig/fonts.conf
